apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicasCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.frontend.containerPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.healthCheckPath }}
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readiness :
            httpGet:
              path: {{ .Values.frontend.healthCheckPath }}
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          resources: {{- toYaml .Values.frontend.resources | nindent 12 }}
