apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-mysql
spec:
  ports:
    - name: http
      port: {{ .Values.mysql.port }}
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-mysql
