apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-backend
spec:
  ports:
    - name: http
      port: {{ .Values.backend.containerPort }}
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-backend
